language: objective-c
before_install:
  - rm -rf Dependencies/ios-etsy-sdk
  - git submodule update --init --recursive
  - chmod a+x travis/before_script.sh
  - chmod a+x travis/script.sh
before_script: travis/before_script.sh
script: travis/script.sh
